#!/bin/bash
set -e
BRANCH=`current_branch`

# force push our branch back, so it auto-closes and links to the PR
if has_remote $BRANCH; then
  git push --force origin $BRANCH
fi

git checkout master
git merge $BRANCH

git push origin master
git checkout $BRANCH
if has_remote $BRANCH; then
  echo "IMPORTANT: Please remember that your local branch has a conflicting history with its remote now, due to rebase onto master. Don't let anyone keep working on the remote; it needs to be blown away via either outright removal or forced push."
fi

